project:
  type: website
  output-dir: docs

website:
  title: "hzauShixin 的个人网站"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 关于我

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
